server:
  port: 8888

logging:
  level:
    org:
      springframework: DEBUG

  sleuth:
    sampler:
      probability: 1

routes:
  authorization: http://${AUTHORIZATION_SERVER_HOST:localhost}:8085
  resource: http://${RESOURCE_SERVER_HOST:localhost}:8086