server:
  port: ${API_GATEWAY_PORT:8888}

spring:
  cloud:
    gateway:
      enabled: true
  application:
    name: api-gateway
  zipkin:
    base-url: http://${ZIPKIN_SERVER_HOST:localhost}:${ZIPKIN_SERVER_PORT:9411}