logging:
  level:
    org:
      springframework: DEBUG

  sleuth:
    sampler:
      probability: 1

routes:
  authorization: http://${AUTHORIZATION_SERVER_HOST:localhost}:${AUTHORIZATION_SERVER_PORT:8085}
  resource: http://${RESOURCE_SERVER_HOST:localhost}:${RESOURCE_SERVER_PORT:8086}