logging:
  level:
    org:
      springframework: DEBUG

security:
  oauth2:
    client:
      client-id: clientx
      client-secret: password

    resource:
      token-info-uri: http://localhost:8085/oauth/check_token
      prefer-token-info: true

  sleuth:
    sampler:
      probability: 1