jdbc:
  jdbcUrl: jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: root
  password: af91949e-d918-11e8-9f8b-f2801f1b9fd1

logging:
  level:
    org:
      springframework: DEBUG

spring:
  datasource:
    platform: mysql
    initialization-mode: always

  sleuth:
    sampler:
      probability: 1