jdbc:
  jdbcUrl: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${MYSQL_DATABASE:oauth2}?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: ${DATABASE_USER:root}
  password: ${DATABASE_PASSWORD:changeit}

logging:
  level:
    org:
      springframework: INFO

spring:
  datasource:
    platform: mysql
    initialization-mode: always

  sleuth:
    sampler:
      probability: 1